- name: Install ElasticSearch (RedHat)
  include: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- fail:
    msg: Only RedHat is currently supported
  when: ansible_os_family not in ['RedHat']

- name: Make sure data directory exists
  file:
    path: '{{ elasticsearch_data_path }}'
    state: directory
    owner: '{{ elasticsearch_user }}'
    group: '{{ elasticsearch_group }}'


- name: Create elasticsearch snapshot directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ elasticsearch_user }}'
    group: '{{ elasticsearch_group }}'
  when: elasticsearch_create_snapshot_dirs and item.startswith('/')
  with_items: elasticsearch_snapshot_paths

- name: "Setup elasticsearch.yml"
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    backup: '{{ elasticsearch_do_backups }}'
  notify:
    - restart elasticsearch

- name: Create keystore
  shell: /usr/share/elasticsearch/bin/elasticsearch-keystore create
  args:
    creates: /etc/elasticsearch/elasticsearch.keystore
  when: elasticssearch_keystore_create

- meta: flush_handlers

- name: Setup elasticsearch service
  service:
    name: '{{ elasticsearch_service_name }}'
    state: '{{ elasticsearch_service_state }}'
    enabled: '{{ elasticsearch_service_enabled }}'

- wait_for:
    port: '{{ elasticsearch_http_port }}'
    timeout: '{{ elasticsearch_wait_timeout }}'
  when: elasticsearch_wait_timeout